services:
  - type: web
    name: my-bot2
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        value: 6993358626
      - key: VIRUSTOTAL_API_KEY
        sync: false
      - key: PORT
        value: 8000
