name: Run Bot
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */5 * * *"
jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: python bot.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          OWNER_ID: ${{ secrets.OWNER_ID }}
